version: 3.9"
services:
  python_main:
    build:
      context: .
      dockerfile: docker/base/Dockerfile
    command: python3 main.py
    ports:
      - "8010:8010"
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
      dbmate:
        condition: service_started
    environment:
      - SRVC_CONFIG=etc/local.json
      - SRVC_LOG=etc/logging.conf

  dbmate:
    image: amacneil/dbmate
    command: -d "/code/etc/db/migrations" up
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/product_catalog_db?sslmode=disable

  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=product_catalog_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
